export const Strings = {
    ADD_REQUEST: 'ADD_REQUEST',
    ADD_SUCCESS: 'ADD_SUCCESS',

    DELETE_REQUEST: 'DELETE_REQUEST',
    DELETE_SUCCESS: 'DELETE_SUCCESS',

    UPDATE_REQUEST: 'UPDATE_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    
    EDIT_REQUEST: 'EDIT_REQUEST',
    EDIT_SUCCESS: 'EDIT_SUCCESS'
};

export default Strings;